#ifndef GRAPHPLUGINELLIPSE_GLOBAL_H
#define GRAPHPLUGINELLIPSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHPLUGINELLIPSE_LIBRARY)
#  define GRAPHPLUGINELLIPSE_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHPLUGINELLIPSE_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHPLUGINELLIPSE_GLOBAL_H
