#ifndef GRAPHPLUGINRECTANGLE_GLOBAL_H
#define GRAPHPLUGINRECTANGLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHPLUGINRECTANGLE_LIBRARY)
#  define GRAPHPLUGINRECTANGLE_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHPLUGINRECTANGLE_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHPLUGINRECTANGLE_GLOBAL_H
