#ifndef PAINTBOARDPLUGIN_GLOBAL_H
#define PAINTBOARDPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAINTBOARDPLUGIN_LIBRARY)
    #  define PAINTBOARDPLUGIN_EXPORT Q_DECL_EXPORT
#else
    #  define PAINTBOARDPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PAINTBOARDPLUGIN_GLOBAL_H
