#ifndef GRAPHPLUGINLINE_GLOBAL_H
#define GRAPHPLUGINLINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHPLUGINLINE_LIBRARY)
#  define GRAPHPLUGINLINE_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHPLUGINLINE_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHPLUGINLINE_GLOBAL_H
